### ISSUE TITLE
Keyboard and Mouse not working?

### ISSUE THREAD

**Issue by EtaoinWu** [kpocza/LoWe#6]
### Question

Keyboard and Mouse not working while follow [the doc of running x window](https://github.com/kpocza/LoWe/blob/master/docs/x.md)

P.S. English is not my native language. Sorry about any grammar or typing mistakes.

### Environment

Windows side: 16257.1000, Visual Studio 15.3.2, .NET Framework 4.7.02542

Both Debug and Release build failed on this.

Linux side: Ubuntu 16.04 xenial, x86_64 Linux 4.4.0-43-Microsoft, gcc version 5.4.0 20160609 (Ubuntu 5.4.0-6ubuntu1~16.04.4), zsh 5.1.1, make 4.1, download from Windows Store. 

Build with `make` command

### What did

1. Run `LoWeExposer.exe` in Windows.
1. Run `loweagent -e X -o x.log` in WSL.
1. Run `unity` in another WSL terminal.

### What happens

A unity Desktop appear in the FrameBuffer Window, but I can't move the cursor in the window. No responce for keyboard as well.

![image](https://user-images.githubusercontent.com/22369305/29614920-a5e3d730-883e-11e7-90ac-218e5fca480c.png)

[Output of  `loweagent -e X -o x.log`](http://paste.ubuntu.com/25376110/)

[Output of `unity`](http://paste.ubuntu.com/25376113/)

[Output of Exposer](http://paste.ubuntu.com/25376126/)

[`x.log` file](http://paste.ubuntu.com/25376188/)

**Comment by EtaoinWu** [comment]
mplayer can play a simple video, but i don't know how to pause or do something else.
xfce4-terminal failed as well: successfully show the window, but can't input anything.

**Comment by kpocza** [comment]
Hi @EtaoinWu,

Don't worry regarding your English, we sail in the same boat as neither I'm a native English speaker. However we are more in number than the native speakers so we rule the English language not them. Just kidding. :)

As I see your Windows version is newer than mine as according to your version you use some kind of insider version. Mine is 15063 aka Creators Update.

However I think that the problem is not with the Windows version. 

For the X/unity issue:
Can it happen that you don't capture the mouse? You should press Left Ctrl + Left Alt and click the left button inside the FrameBuffer Exposer window. The same combination will release the mouse.

For the mplayer issue:
You should hit the controlling keys (like p for pause) not in the FrameBuffer Exposer but in the Bash window where you started mplayer.

Please check if with this explanation you can control you applications and get back to me. 

If you say that the explanation solves your problems then I'll clarify the documentation as currently only LoweExposer program explains input device usage.

**Comment by EtaoinWu** [comment]
Thank you @kpocza .

Hit the keys in Bash window solved my problem about mplayer.

---

As for the X issue, I found this below:

* I can coltrol neither mouse nor keyboard before I hit Lctrl-Lalt-LMouseClick, There is no output in LoWe Exposer's Mouse log window.
* After I hit C-M-click, the output is like this:
	```plain
	X: 717, Y: 291, L: False, R: False
	X: 717, Y: 289, L: False, R: False
	X: 718, Y: 289, L: False, R: False
	X: 718, Y: 288, L: False, R: False
	X: 718, Y: 287, L: False, R: False
	...
	And more lines like this.
	```
* But I can't still control the mouse inside the Exposer.

**Comment by kpocza** [comment]
Hi @EtaoinWu,

For the X issue.
Have you correctly created `/usr/share/X11/xorg.conf.d/9-lowe.conf` with the right content (copy the file from the `config` folder)?
This is a prerequisite.

Could you please raise the log level of the agent to Debug?
eg. `./loweagent -e X -o x.log -l Debug`

If mouse and keyboard are working the you should see fragments like this in the log:
"
[DEBUG][P 46][FD 9]{mice}: -= Before read =-
[DEBUG][P 46][FD 9]{mice}: Read regs. rdi: 9 rsi: 140737048986160 rdx: 6144
[DEBUG][P 46][FD 9]{mice}: Read size: 6144
[DEBUG][P 46][FD 9]{mice}: -= After read =-
[DEBUG][P 46][FD 9]{mice}: Read size: 0
[DEBUG][P 46][FD 9]{mice}: regs. rax: 0 rdi: 9 rsi: 140737048986160 rdx: 6144 r10: 8 r8:  140737188924656 r9: 0
[DEBUG][P 46]{runtime}: ---
[DEBUG][P 46]{runtime}: SYSCALL: 14
[DEBUG][P 46]{runtime}: SYSCALL: 14
[DEBUG][P 46]{runtime}: SYSCALL: 0
[DEBUG][P 46][FD 10]{kbd}: -= Before read =-
[DEBUG][P 46][FD 10]{kbd}: Read regs. rdi: 10 rsi: 140737049013216 rdx: 6192
[DEBUG][P 46][FD 10]{kbd}: Read size: 6192
[DEBUG][P 46][FD 10]{kbd}: -= After read =-
[DEBUG][P 46][FD 10]{kbd}: Read size: 0
[DEBUG][P 46][FD 10]{kbd}: regs. rax: 0 rdi: 10 rsi: 140737049013216 rdx: 6192 r10: 8 r8:  140737188924656 r9: 0
"

**Comment by EtaoinWu** [comment]
Oops, I didn't found the sentence

> Copy the 9-lowe.conf from the configs folder of the local git repository to `/usr/share/X11/xorg.conf.d/9-lowe.conf.`

in the doc.

So the application do work on Windows build 16257. Apologize to you for taking so much of your time.
